---
- name: redhat-installing-nfs-package
  yum:
    name: "nfs-utils"
    state: "present"
  become: true
  when: ansible_distribution != "Fedora"
  tags: 
    - package

- name: redhat-installing-nfs-package
  dnf:
    name: "nfs-utils"
    state: "present"
  become: true
  when: ansible_distribution == "Fedora"
  tags: 
    - package
